### ISSUE TITLE
Add editor fields for the Compound data map

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-editor#10]
[PR #478 in ord-schema](https://github.com/Open-Reaction-Database/ord-schema/pull/478) proposes adding a `map<string, Data> data` field to Compound message. If this is approved and merged, the editor will need to be updated. Input-associated, workup-associated, and product-associated compounds will need to load/unload data.

**Comment by skearnes** [comment]
Closing since that PR has been superseded by https://github.com/Open-Reaction-Database/ord-schema/pull/496 and we will need to do lots of follow-up work related to that change in ord-editor and ord-data.
