### ISSUE TITLE
Creating a new (empty) reaction gives 3 validation errors, but the bulleted list isn't legible

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-editor#100]

**Comment by skearnes** [comment]
I believe this is fixed in #96

**Comment by connorcoley** [comment]
I've been working off of that branch (and made some additions at https://github.com/skearnes/ord-editor/pull/1, which might not have been the best way to do it) and this was still an issue.

There actually wasn't anything in the `<li>` elements for me:

![image](https://user-images.githubusercontent.com/4213670/115252662-acb86a80-a0f9-11eb-8b3b-c0b32b92eaf7.png)

**Comment by skearnes** [comment]
OK, fixed now
