### ISSUE TITLE
Web Editor and Large Dataset Enumeration

### ISSUE THREAD

**Issue by mwleklin** [open-reaction-database/ord-editor#16]
Enumerating Large datasets is very sluggish (# rxns 5760). I am unable to view the result file and get the attached error. 

![image](https://user-images.githubusercontent.com/44303709/96728791-6ff5fb80-1382-11eb-8bf4-9f6b78008dc1.png)

**Comment by skearnes** [comment]
Some timings from local (non-editor) runs:

```shell
$ time python ord_schema/scripts/enumerate_dataset.py --spreadsheet ../ord-data/AAP9112.csv --template ../ord-data/reaction_1_enum.pbtxt --output test.pbtxt 
I1021 09:55:42.963978 4524916160 enumerate_dataset.py:50] generating new Dataset from ../ord-data/reaction_1_enum.pbtxt and ../ord-data/AAP9112.csv
I1021 09:56:43.646265 4524916160 enumerate_dataset.py:59] writing new Dataset to test.pbtxt
python ord_schema/scripts/enumerate_dataset.py --spreadsheet  --template     69.40s user 0.57s system 98% cpu 1:10.68 total

$ time python ord_schema/scripts/enumerate_dataset.py --spreadsheet ../ord-data/AAP9112.csv --template ../ord-data/reaction_1_enum.pbtxt --output test.pb  
I1021 09:58:41.967513 4699291072 enumerate_dataset.py:50] generating new Dataset from ../ord-data/reaction_1_enum.pbtxt and ../ord-data/AAP9112.csv
I1021 09:59:45.214761 4699291072 enumerate_dataset.py:59] writing new Dataset to test.pb
python ord_schema/scripts/enumerate_dataset.py --spreadsheet  --template     64.21s user 0.57s system 98% cpu 1:05.61 total
```

This is definitely CPU-bound; I'll work on parallelizing the template enumeration.

**Comment by skearnes** [comment]
Update: Around half the time is spent validating each Reaction as it is enumerated (and just validating the Dataset at the end is not any faster).

**Comment by skearnes** [comment]
@antonkast-google @connorcoley I see a few options here:

1. Do nothing. Add a note that if users have trouble with enumeration they should use the command line or create an issue on ord-data. This would be part of our general "documentation is nearby" effort for the editor that we discussed yesterday.
1. Use e.g. joblib to parallelize the enumeration. This could avoid timeouts but also increases the resources required for the server VM (which won't be fully utilized most of the time).
1. Make enumeration asynchronous. The dataset would appear if it successfully completed and otherwise we would find a way to communicate the errors.

WDYT?

**Comment by antonkast-google** [comment]
At this point, I think they should send us the stuff in email.

How many emails a day would it take before it's no longer worth our time to produce the PRs ourselves?

**Comment by connorcoley** [comment]
I think that using joblib to parallelize enumeration/validation is the simplest and best solution if we expect the largest contributions to be O(10^4) reactions. If want a more flexible solution, I would suggest having the enumeration be asynchronous. Implementation issues aside, asynchronous enumeration would be the most attractive from a user perspective IMO

**Comment by antonkast-google** [comment]
I'm serious. Is there an argument why this needs to be a web site feature?

They can email their stuff to me. I will run a script to do the merge, push it to the editor, and send them the link. I estimate the task will take me five minutes per email. If I find I'm doing it more than once a week, then I'll take on this issue.

**Comment by skearnes** [comment]
I think the primary concern here is about interrupting the user workflow. But I was able to turn around Mike's large dataset in a few minutes today so I'm happy with option (1) as long as we add some documentation to the editor so that people know (a) this is expected and (b) they have support.

**Comment by mwleklin** [comment]
I think option (1) is fine for the time being, but I would say that some folks (me included) are inclined to see the results of enumeration to "manually inspect" portions of it before submission. Have you thought much about DEL or other potentially larger sources of chemical reaction data where the dataset could be 10^6-10^9 in size?

**Comment by skearnes** [comment]
Possibility: update the flask template for timeouts.

**Comment by skearnes** [comment]
Note: leaving this open until the editor landing page makes it clear that timeouts are expected and provides helpful links to deal with them instead of the ominous error page from OP.
