### ISSUE TITLE
Web Editor Graphic Bug

### ISSUE THREAD

**Issue by mwleklin** [open-reaction-database/ord-editor#18]
For long reactions on small screen the side bar and drawing can overlap making it difficult to read below.

![image](https://user-images.githubusercontent.com/44303709/96723317-6d90a300-137c-11eb-88e1-75535de88ecd.png)

**Comment by skearnes** [comment]
@mwleklin Can you link to a page where this is happening? I haven't been able to reproduce.

**Comment by mwleklin** [comment]
Here's the specific link
https://editor.open-reaction-database.org/dataset/Suzuki-Miyaura%20cross-coupling_MW_1_Change.pbtxt/reaction/0?user=144fbf60a4884a0789b5e4a7eef87581

It only occurs on my 14" laptop monitor and not on my larger external monitor.

**Comment by skearnes** [comment]
Thanks. I can confirm that there's an overlap issue with the sidebar.

**Comment by n8kim1** [comment]
@skearnes @mwleklin I can't get this to reproduce anymore, would someone be able to check? Wonder if we fixed this in other graphics changes. Sorry for the delay.
(Also the link doesn't work anymore too...)

**Comment by skearnes** [comment]
I can't reproduce now either; this might be fixed. @mwleklin can you confirm?

**Comment by skearnes** [comment]
Closing since we can't repro and haven't heard from @mwleklin.

**Comment by mwleklin** [comment]
Can confirm this bug no longer occurs.
