### ISSUE TITLE
Scrolling in frozen mode will not hide elements behind the header

### ISSUE THREAD

**Issue by n8kim1** [open-reaction-database/ord-editor#26]
(@skearnes, please correct me if this isn't correct / if this is a dupe I'm not seeing)

**Comment by skearnes** [comment]
Note that this only seems to affect the frozen dropdown selectors; text fields are hidden as expected.

![image](https://user-images.githubusercontent.com/952729/98597334-1bb1ad80-2296-11eb-8a9a-3b11b5a14f39.png)
