### ISSUE TITLE
GitHub user icon does not have a limited height, can extend header and obscure form

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-editor#42]
![Screen Shot 2020-11-10 at 4 10 13 PM](https://user-images.githubusercontent.com/4213670/98754281-526ded80-2394-11eb-807a-b473a5943fe3.png)

See photo. The solution may just be specifying a height of 24 px in the CSS for the #identity img.

Reproducible using Safari on Mac

**Comment by skearnes** [comment]
Note that this also affects /datasets and /dataset; anywhere the login section is present.
