### ISSUE TITLE
Add "undo" for section removal

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-editor#5]
Alternatively, ask for confirmation before removal

**Comment by skearnes** [comment]
I was thinking about this, and came up a solution that doesn't require backup to proto: simply hide the elements in the form instead of actually removing them, and make sure that the `unload` functions ignore hidden elements. Then "undo" becomes toggling visibility, and the undo cache resets on page reload (since the hidden elements are not saved in the written protos).

**Comment by skearnes** [comment]
I've been thinking about this more in light of the complexity that Anton highlighted last week. I'd be ok with implementing a version that doesn't use a stack---only a single undo is permitted---or just dropping this and keeping our alert that requests confirmation.

WDYT?

**Comment by connorcoley** [comment]
An alert to require confirmation on a "delete" or "remove" action seems sufficient to me

**Comment by antonkast-google** [comment]
A one-level undo sounds good because it's simple. I would put the undo button in the place where the delete button had been, and clean that up when the next delete occurs.

I'm not sure I like a modal dialog every time something is deleted, because I imagine it may be a frequent operation.

**Comment by skearnes** [comment]
Closed by #61
