### ISSUE TITLE
Add auto-save to the web editor

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-editor#6]
We had one alpha tester report data loss after leaving the page without saving.

**Comment by n8kim1** [comment]
What's a good interval for autosave? (Thinking about 1 minute.)

**Comment by skearnes** [comment]
> What's a good interval for autosave? (Thinking about 1 minute.)

+1 for 1 minute

**Comment by antonkast-google** [comment]
Rather than periodic writes, which would cause idle clients to load the server, I would save after any modification (a text field loses focus or a selector changes selection) with a timeout for batching.

**Comment by skearnes** [comment]
@antonkast-google good point. I think this would be simply achieved by checking whether the save button is visible. Then we can still do periodic attempts to auto-save, but it won't trigger a write unless there have been modifications.
