### ISSUE TITLE
String values for ER selectivities are silently lost from the form

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-editor#76]
If an ER is defined in a ProductMeasurement of type SELECTIVITY as a string value, it will not be included in the saved/stored pbtxt file. The treatment of ERs as strictly numeric values (i.e., the "x" in an "x:1 ratio") is correct, but this should not happen without an error/warning message.

**Comment by skearnes** [comment]
I can't reproduce this; can you give an example?

**Comment by connorcoley** [comment]
Correction: the value is present in the form but it is NOT present in the pbtxt when you try to download. Not sure how to give an example when the editor shows it but the downloaded pbtxt doesn't :)

I just added a measurement of type SELECTIVITY, selectivity type ER, and string value "50"

**Comment by skearnes** [comment]
Oh, I haven't been able to reproduce that, either. When I enter various values in the ER details field, they show up in the pbtxt.

I tried with both strings like "76:1" as well as numbers like "76".

**Comment by skearnes** [comment]
Maybe the difference is that I'm modifying an otherwise valid reaction. Are you starting from scratch? Do you have a defined analysis that the measurement is paired with?

**Comment by connorcoley** [comment]
![image](https://user-images.githubusercontent.com/4213670/105579956-89c72600-5d57-11eb-8b04-5cda12b8613e.png)

![image](https://user-images.githubusercontent.com/4213670/105579972-977cab80-5d57-11eb-80b0-0dbf743568da.png)

[reaction.pbtxt.zip](https://github.com/open-reaction-database/ord-editor/files/5860285/reaction.pbtxt.zip)

**Comment by skearnes** [comment]
Ah ok, I thought you were referring to the Selectivity message below that only has a details field. Are those redundant?

**Comment by skearnes** [comment]
(At least the comments in reaction.proto suggest that the value should be entered in the second `details` field.)

**Comment by connorcoley** [comment]
I think the selectivity details is not useful _except_ when the type is CUSTOM. The value should presumably by in the above float_value, string_value, or percentage_value

**Comment by skearnes** [comment]
Got it; I misread the comments (they correctly reflect your understanding).

**Comment by skearnes** [comment]
(working on a fix, but I found another bug after I fixed that one...)
