### ISSUE TITLE
Maps without names aren't unloaded from the form into a proto

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-editor#99]
If an input has no name, or if an automation code or analysis has no name, then they will be silently excluded from the message. We should have a way of checking this. When a new map field is created, should we automatically populate the name field like we do with the sidebar?

**Comment by skearnes** [comment]
I can't reproduce this on my branch; the input/analysis shows up in the proto without a "key" field and seems to reload just fine.

**Comment by connorcoley** [comment]
I can't figure out what example led me to observe this either anymore. Will reopen if I find one, but the code looks right
